atay_trade/atay_trade/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('y4g1z4t4y/', admin.site.urls),
    path("", include("store.urls")),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

atay_trade/store/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "store"

urlpatterns = [
    path("", views.store, name="store"),
    path("cart/", views.CartList.as_view()),
    path("cart/add/", views.CartAdd.as_view()),
    path("cart/remove/", views.CartRemove.as_view()),
    path("checkout/", views.checkout, name="checkout"),
    path("contact/", views.contact, name="contact"),
    path("catalog/", views.catalog, name="catalog"),
    path("catalog/<str:category>", views.catalog, name="catalogByCategory"),
    path("products/<int:id>", views.product, name="product"),
    path("signup/", views.signup, name="signup"),
    path("account/", views.account, name="account"),
    path("login/", auth_views.LoginView.as_view(template_name="store/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(template_name="store/index.html"), name="logout"),
    path("wishlist/", views.wishlist, name="wishlist"),
    path("wishlist/add/", views.wishlistAdd),
    path("wishlist/remove/", views.wishlistRemove),
    path("orders/process/", views.processOrder),
    path("stocks/check/", views.checkStocks),
    path("invoices/<str:transaction_id>", views.invoice, name="invoice")
]

atay_trade/templates/components/arrivalsArea.html
{% load static %}
{% load store_extras %}
<!-- ##### New Arrivals Area Start ##### -->
<section class="new_arrivals_area section-padding-80 clearfix">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section-heading text-center">
                    <h2>Latest Arrivals</h2>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="popular-products-slides owl-carousel">

                    {% for product in latestArrivedProducts %}
                    <!-- Single Product -->
                    <div class="single-product-wrapper">
                        <!-- Product Image -->
                        <div class="product-img">
                            <a href="{% url 'store:product' id=product.id %}">
                                <img src='{{productThumbnails|index:product.id|index:0}}' alt="{{product.name}} thumbnail image 1" />
                                <!-- Hover Thumb -->
                                <img class="hover-img" src='{{productThumbnails|index:product.id|index:1}}' alt="{{product.name}} thumbnail image 2" />
                            </a>  

                            {% if user.is_authenticated %}
                            <!-- Favourite -->
                            <div class="product-favourite">
                                {% if productWishlistStatuses|index:product.id %}
                                <a data-product="{{product.id}}" class="favme fa fa-heart active"></a>
                                {% else %}
                                <a data-product="{{product.id}}" class="favme fa fa-heart"></a>
                                {% endif %}
                            </div>
                            {% endif %}

                            <!-- Product Badge -->
                            <div class="product-badge new-badge">
                                <span>New</span>
                            </div>

                        </div>
                        <!-- Product Description -->
                        <div class="product-description">
                            {% if product.brand %}
                                <span>{{product.brand}}</span>
                            {% endif %}
                                
                            <a href="{% url 'store:product' id=product.id %}">
                                <h6>{{product.name}}</h6>
                            </a>
                            <p class="product-price">£{{product.price|floatformat:2}}</p>

                            <!-- Hover Content -->
                            <div class="hover-content">
                                <!-- Add to Cart -->
                                <div class="add-to-cart-btn">
                                    {% if product.stock == 0 %}
                                        <button disabled data-product="{{product.id}}" class="btn essence-btn add-cart">Out of stock</button>
                                    {% else %}
                                        <button data-product="{{product.id}}" class="btn essence-btn add-cart">Add to Cart</button>    
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                        
                </div>
            </div>
        </div>
    </div>
</section>
<!-- ##### New Arrivals Area End ##### -->

atay_trade/templates/components/brands.html
{% load static %}
<!-- ##### Brands Area Start ##### -->
<div class="brands-area d-flex align-items-center justify-content-between">
    <!-- Brand Logo -->
    <div class="single-brands-logo">
        <img src='{% static "img/core-img/brand1.png" %}' alt="">
    </div>
    <!-- Brand Logo -->
    <div class="single-brands-logo">
        <img src='{% static "img/core-img/brand2.png" %}' alt="">
    </div>
    <!-- Brand Logo -->
    <div class="single-brands-logo">
        <img src='{% static "img/core-img/brand3.png" %}' alt="">
    </div>
    <!-- Brand Logo -->
    <div class="single-brands-logo">
        <img src='{% static "img/core-img/brand4.png" %}' alt="">
    </div>
    <!-- Brand Logo -->
    <div class="single-brands-logo">
        <img src='{% static "img/core-img/brand5.png" %}' alt="">
    </div>
    <!-- Brand Logo -->
    <div class="single-brands-logo">
        <img src='{% static "img/core-img/brand6.png" %}' alt="">
    </div>
</div>
<!-- ##### Brands Area End ##### -->

atay_trade/templates/components/breadcrumbArea.html
{% load static %}


{% if uppercase %}
    <div class="breadcumb_area bg-img" style="background-image: url('{% static "img/bg-img/breadcumb.jpg" %}')">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <div class="col-12">
                    <div class="page-title text-center">
                        <h2>{{title}}</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% else %}
    <div class="breadcumb_area bg-img" style="background-image: url('{% static "img/bg-img/breadcumb.jpg" %}')">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <div class="col-12">
                    <div class="page-title text-center">
                        <h2 style="text-transform:capitalize !important">{{title}}</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endif %}

atay_trade/templates/components/commonTravelArea.html
{% load static %}
<!-- ##### CTA Area Start ##### -->
<div class="cta-area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="cta-content bg-img background-overlay" style="background-image: url('{% static "img/bg-img/bg-5.jpg" %}')">
                    <div class="h-100 d-flex align-items-center justify-content-center">
                        <div class="text-center"> <!--cta--text-->
                            <h6>Up to -60%</h6>
                            <h2>Giant Sales</h2>
                            <a href="{% url 'store:catalog' %}" class="btn essence-btn">Buy Now</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ##### CTA Area End ##### -->

atay_trade/templates/components/contactInfo.html
<div class="contact-area d-flex align-items-center">

    <div class="google-map">
        <div id="googleMap">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2381.827281525096!2d-3.096280033978487!3d53.346347932411895!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487ad801a0135583%3A0x37c3376038f71ad4!2sPensby%20Rd%2C%20Heswall%2C%20Birkenhead%2C%20Wirral%20CH61%209NH!5e0!3m2!1sen!2suk!4v1613049238204!5m2!1sen!2suk" style="width: 100%;height: 100%;border:0;"  frameborder="0" allowfullscreen="true" aria-hidden="false" tabindex="0"></iframe>
        </div>
    </div>

    <div class="contact-info">
        <h2>How to Find Us</h2>
        <p>Please don't hesitate to contact us if you have any questions or concerns. Our team is constantly working to provide you the best assistance via phone and email.</p>

        <div class="contact-address mt-50">
            <p><span>address:</span> 404 Pensby Road Wirral, UK, CH61 9NH</p>
            <p><span>telephone:</span> 
                <a class="btn btn-outline-warning" style="color: #787878 !important;font-size: 12px;font-weight: 600;" href="https://wa.me/447437376080/?text=Hello%2C+I+need+assistance%21">
                    +44 7437 376 080
                </a>
            </p>
            <p style="margin-top: 0px !important;"><span>email:</span>
                <a class="btn btn-outline-warning" style="color: #787878 !important;font-size: 12px;font-weight: 600;" href="mailto:ataycommerce@gmail.com">
                    ataycommerce@gmail.com
                </a>
            </p>
            
        </div>
    </div>

</div>

atay_trade/templates/components/dynamicCart.html
{% load static %}
 <!-- ##### Right Side Cart Area ##### -->
 <div class="cart-bg-overlay"></div>

 <div class="right-side-cart-area">

     <!-- Cart Button -->
     <div class="cart-button">
         <a id="rightSideCart"><img src="{% static 'img/core-img/bag.svg' %}" alt=""> <span class="count-cart"></span></a>
     </div>

     <div class="cart-content d-flex">

         <!-- Cart List Area -->
         <div class="cart-list">
         </div>

         <!-- Cart Summary -->
         <div class="cart-amount-summary">

             <h2>Summary</h2>
             <ul class="summary-table">
                 <li><span>subtotal:</span> <span class="subtotal"></span></li>
                 <li><span>delivery:</span> <span class="delivery">Free</span></li>
                 <!--<li><span>discount:</span> <span>-15%</span></li>-->
                 <li><span>total:</span> <span class="summary-total"></span></li>
             </ul>
             <div class="checkout-btn mt-100">
                 <a href="{% url 'store:checkout' %}" class="btn essence-btn">check out</a>
             </div>
         </div>
     </div>
 </div>
 <!-- ##### Right Side Cart End ##### -->

atay_trade/templates/components/footer.html
{% load static %}
<!-- ##### Footer Area Start ##### -->
<footer class="footer_area clearfix">
    <div class="container">
        <div class="row">
            <!-- Single Widget Area -->
            <div class="col-12 col-md-6">
                <div class="single_widget_area d-flex mb-30">
                    <!-- Logo -->
                    <div class="footer-logo mr-50" style="background-color: #ebebeb;border: 4px solid #0315ff; border-radius: 10px;">
                        <a class="dynamic-width" href="{% url 'store:store' %}"><img src="{% static 'img/core-img/logo.png' %}"></a>
                    </div>
                    <!-- Footer Menu -->
                    <div class="footer_menu">
                        <ul>
                            <li><a href="{% url 'store:catalog' %}" style="font-size: 1.25rem !important;">Shop</a></li>
                            <li><a href="{% url 'store:contact' %}" style="font-size: 1.25rem !important;">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- Single Widget Area -->
            <div class="col-12 col-md-6">
                <div class="single_widget_area mb-30">
                    <ul class="footer_widget_menu">
                        <li><a href="/">Order Status</a></li>
                        <li><a href="/">Payment Options</a></li>
                        <li><a href="/">Shipping and Delivery</a></li>
                        <li><a href="/">Privacy Policy</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="row align-items-end">
            <!-- Single Widget Area -->
            <div class="col-12 col-md-6">
                <div class="single_widget_area">
                    <div class="footer_heading mb-30">
                        <h6>Subscribe</h6>
                    </div>
                    <div class="subscribtion_form">
                        <form action="/" method="post">
                            {% csrf_token %}
                            <input type="email" name="mail" class="mail" placeholder="Your email here">
                            <button type="submit" class="submit"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></button>
                        </form>
                    </div>
                </div>
            </div>
            <!-- Single Widget Area -->
            <div class="col-12 col-md-6">
                <!--<div class="single_widget_area">
                    <div class="footer_social_area">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Instagram"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Pinterest"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Youtube"><i class="fa fa-youtube-play" aria-hidden="true"></i></a>
                    </div>
                </div>-->
            </div>
        </div>

<div class="row mt-5">
            <div class="col-md-12 text-center">
                <p>
                    Copyright © 2020 All rights are reserved. Developed by <a href="https://goldenhandsoftware.co.uk" target="_blank">Goldenhand Software</a>
                </p>
            </div>
        </div>

    </div>
</footer>
<!-- ##### Footer Area End ##### -->

atay_trade/templates/components/navbar.html
{% load static %}
<!-- ##### Header Area Start ##### -->
<header class="header_area">
    <div class="classy-nav-container breakpoint-off d-flex align-items-center justify-content-between">
        <!-- Classy Menu -->
        <nav class="classy-navbar" id="essenceNav">
            <!-- Logo -->
            <a class="nav-brand dynamic-width" href="{% url 'store:store' %}"><img src="{% static 'img/core-img/logo.png' %}"></a>
            <!-- Navbar Toggler -->
            <div class="classy-navbar-toggler">
                <span class="navbarToggler"><span></span><span></span><span></span></span>
            </div>
            <!-- Menu -->
            <div class="classy-menu">
                <!-- close btn -->
                <div class="classycloseIcon">
                    <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                </div>
                <!-- Nav Start -->
                <div class="classynav">
                    <ul>
                        <li><a href="" class="text-dark font-italic">Shop</a>
                            <div class="megamenu">
                                <ul class="single-mega cn-col-4">
                                    <li class="title font-bold">Categories</li>           
                                    <li><a href="{% url 'store:catalogByCategory' 'bracelets' %}">Bracelets</a></li>
                                    <li><a href="{% url 'store:catalogByCategory' 'earrings' %}">Earrings</a></li>
                                    <li><a href="{% url 'store:catalogByCategory' 'necklaces' %}">Necklaces</a></li>
                                    <li><a href="{% url 'store:catalogByCategory' 'hats' %}">Hats</a></li>
                                    <li><a href="{% url 'store:catalogByCategory' 'socks' %}">Socks</a></li>
                                    <li><a href="{% url 'store:catalogByCategory' 'accessories' %}">Accessories</a></li>
                                    <li><a href="{% url 'store:catalogByCategory' 'rings' %}">Rings</a></li>
                                </ul>
                                <ul class="single-mega cn-col-4">
                                    <img src="{% static 'img/bg-img/bg-6.jpg' %}" alt="">
                                </ul>
                            </div>
                        </li>
                        
                        <li><a href="{% url 'store:contact' %}" class="text-dark font-italic">Contact</a></li>
                    </ul>
                </div>
                <!-- Nav End -->
            </div>
        </nav>

        <!-- Header Meta Data -->
        <div class="header-meta d-flex clearfix justify-content-end">
            <!-- Search Area -->
            <div class="search-area">
                <form action="{% url 'store:catalog' %}" method="get">
                    <input type="search" name="search" id="headerSearch" placeholder="Type for search">
                    <button type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                </form>
            </div>

            {% if user.is_authenticated %}
            <!-- Wishlist -->
            <div class="favourite-area">
                <a href="{% url 'store:wishlist' %}"><img src="{% static 'img/core-img/heart.svg' %}" alt=""></a>
            </div>
            {% endif %}

            <!-- User Login Info -->
            <div class="user-login-info">
                {% if user.is_authenticated %}
                <a href="{% url 'store:account' %}"><img src="{% static 'img/core-img/user.svg' %}" alt=""></a>
                {% else %}
                <a href="{% url 'store:login' %}"><img src="{% static 'img/core-img/user.svg' %}" alt=""></a>
                {% endif %}
            </div>
            
            <!-- Cart Area -->
            <div class="cart-area">
                <a class="get-cart" id="essenceCartBtn"><img src="{% static 'img/core-img/bag.svg' %}" alt=""> <span class="count-cart"></span></a>
            </div>
        </div>

    </div>
</header>
<!-- ##### Header Area End ##### -->

atay_trade/templates/components/productDetailArea.html
{% load static %}

<!-- ##### Single Product Details Area Start ##### -->
<section class="single_product_details_area d-flex align-items-center">

    <!-- Single Product Thumb -->
    <div class="single_product_thumb clearfix">
        <div class="product_thumbnail_slides owl-carousel">
            {% for productImage in productImages %}
                <img src="{{ productImage.resized_image.url }}" alt="">
            {% endfor %}
        </div>
    </div>

    <!-- Single Product Description -->
    <div class="single_product_desc clearfix">
        {% if product.brand %}
            <span>{{product.brand}}</span>
        {% endif %}

        <h2>{{ product.name }}</h2>
        
        {% if product.stock == 0 %}
            <p style="color: red;"> The product is not in our inventory yet.</p>
        {% endif %}

        
        {% if product.discounted_price %}
            <p class="product-price"><span class="old-price">£{{product.price|floatformat:2}}</span> £{{product.discounted_price|floatformat:2}}</p>    
        {% else %}
            <p class="product-price"> £{{product.price|floatformat:2}}</p> 
        {% endif %}
        
        <p class="product-desc">{{product.description}}</p>


        <div class="cart-fav-box d-flex align-items-center mt-50">
            <!-- Cart -->
            {% if product.stock == 0 %}
                <button disabled data-product="{{product.id}}" class="btn essence-btn add-cart">Out of stock</button>
            {% else %}
                <button data-product="{{product.id}}" class="btn essence-btn add-cart">Add to Cart</button>    
            {% endif %}

            {% if user.is_authenticated %}
                
                {% if productWishlisted %}
                <!-- Favourite -->
                <div class="product-favourite ml-4">
                    <a data-product="{{product.id}}" class="favme fa fa-heart active"></a>
                </div>
                {% else %}
                <!-- Favourite -->
                <div class="product-favourite ml-4">
                    <a data-product="{{product.id}}" class="favme fa fa-heart"></a>
                </div>
                {% endif %}

            {% endif %}
        </div>

        
        <!--<form class="cart-form clearfix" method="post">

                <div class="select-box d-flex mt-50 mb-30">
                    <select name="select" id="productSize" class="mr-5">
                        <option value="value">Size: XL</option>
                        <option value="value">Size: X</option>
                        <option value="value">Size: M</option>
                        <option value="value">Size: S</option>
                    </select>
                    <select name="select" id="productColor">
                        <option value="value">Color: Black</option>
                        <option value="value">Color: White</option>
                        <option value="value">Color: Red</option>
                        <option value="value">Color: Purple</option>
                    </select>
                </div>
            
        
            <div class="cart-fav-box d-flex align-items-center">
                <button type="submit" name="addtocart" value="5" class="btn essence-btn">Add to cart</button>

                <div class="product-favourite ml-4">
                    <a href="#" class="favme fa fa-heart"></a>
                </div>
            </div>
        </form>-->
    </div>
</section>
<!-- ##### Single Product Details Area End ##### -->

atay_trade/templates/components/salesArea.html
{% load static %}
{% load store_extras %}
<!-- ##### New Sales Area Start ##### -->
<section class="new_arrivals_area clearfix" style="padding-bottom: 80px;">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section-heading text-center">
                    <h2>Ongoing Sales</h2>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="popular-products-slides owl-carousel">

                    {% for product in onSaleProducts %}
                    <!-- Single Product -->
                    <div class="single-product-wrapper">
                        <!-- Product Image -->
                        <div class="product-img">
                            <a href="{% url 'store:product' id=product.id %}">
                                <img src='{{productThumbnails|index:product.id|index:0}}' alt="{{product.name}} thumbnail image 1" />
                                <!-- Hover Thumb -->
                                <img class="hover-img" src='{{productThumbnails|index:product.id|index:1}}' alt="{{product.name}} thumbnail image 2" />
                            </a>
                            
                            {% if user.is_authenticated %}
                            <!-- Favourite -->
                            <div class="product-favourite">
                                {% if productWishlistStatuses|index:product.id %}
                                <a data-product="{{product.id}}" class="favme fa fa-heart active"></a>
                                {% else %}
                                <a data-product="{{product.id}}" class="favme fa fa-heart"></a>
                                {% endif %}
                            </div>
                            {% endif %}
                            
                            <!-- Product Badge -->
                            <div class="product-badge offer-badge">
                                <span>-{{product.calculate_sale_percantage_number }}%</span>
                            </div>

                        </div>
                        <!-- Product Description -->
                        <div class="product-description">
                            {% if product.brand %}
                                <span>{{product.brand}}</span>
                            {% endif %}
                            <a href="{% url 'store:product' id=product.id %}">
                                <h6>{{product.name}}</h6>
                            </a>

                            <p class="product-price"><span class="old-price">£{{product.price|floatformat:2}}</span> £{{product.discounted_price|floatformat:2}}</p>

                            <!-- Hover Content -->
                            <div class="hover-content">
                                <!-- Add to Cart -->
                                <div class="add-to-cart-btn">
                                    {% if product.stock == 0 %}
                                        <button disabled data-product="{{product.id}}" class="btn essence-btn add-cart">Out of stock</button>
                                    {% else %}
                                        <button data-product="{{product.id}}" class="btn essence-btn add-cart">Add to Cart</button>    
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                        
                </div>
            </div>
        </div>
    </div>
</section>
<!-- ##### New Arrivals Area End ##### -->

atay_trade/templates/components/topCategoryArea.html
{% load static %}
{% load store_extras %}
<!-- ##### Top Catagory Area Start ##### -->
<div class="top_catagory_area section-padding-80 clearfix">
    <div class="container">
        <div class="row justify-content-center">
            
            {% for category in categories  %}            
                {% if forloop.counter0 < 3 %}
                <div class="col-12 col-sm-6 col-md-4">
                    <div class="single_catagory_area d-flex align-items-center justify-content-center bg-img" style="background-image: url({{categoryImages|index:category.name}})">
                        <div class="catagory-content">
                            <a href="{% url 'store:catalogByCategory' category.name|lower %}">{{category.name}}</a>
                        </div>
                    </div>
                </div> 
                {% else %}
                <div class="col-12 col-sm-6 col-md-4 mt-md-4">
                    <div class="single_catagory_area d-flex align-items-center justify-content-center bg-img" style="background-image: url({{categoryImages|index:category.name}})">
                        <div class="catagory-content">
                            <a href="{% url 'store:catalogByCategory' category.name|lower %}">{{category.name}}</a>
                        </div>
                    </div>
                </div> 
                {% endif %}
            {% endfor %}
           
        </div>
    </div>
</div>
<!-- ##### Top Catagory Area End ##### -->

atay_trade/templates/components/welcomeArea.html
{% load static %}
<!-- ##### Welcome Area Start ##### -->
<section class="welcome_area bg-img background-overlay" style="background-image: url('{% static "img/bg-img/bg-1.jpg" %}')">
    <div class="container h-100">
        <div class="row h-100 align-items-center">
            <div class="col-12">
                <div class="hero-content">
                    <h6 style="color: black;">Wear better, look better!</h6>
                    <h2 style="color: black;">New Collection</h2>
                    <a href="{% url 'store:catalog' %}" class="btn essence-btn">view collection</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- ##### Welcome Area End ##### -->