atay_trade/atay_trade/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('y4g1z4t4y/', admin.site.urls),
    path("", include("store.urls")),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

atay_trade/store/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "store"

urlpatterns = [
    path("", views.store, name="store"),
    path("cart/", views.CartList.as_view()),
    path("cart/add/", views.CartAdd.as_view()),
    path("cart/remove/", views.CartRemove.as_view()),
    path("checkout/", views.checkout, name="checkout"),
    path("contact/", views.contact, name="contact"),
    path("catalog/", views.catalog, name="catalog"),
    path("catalog/<str:category>", views.catalog, name="catalogByCategory"),
    path("products/<int:id>", views.product, name="product"),
    path("signup/", views.signup, name="signup"),
    path("account/", views.account, name="account"),
    path("login/", auth_views.LoginView.as_view(template_name="store/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(template_name="store/index.html"), name="logout"),
    path("wishlist/", views.wishlist, name="wishlist"),
    path("wishlist/add/", views.wishlistAdd),
    path("wishlist/remove/", views.wishlistRemove),
    path("orders/process/", views.processOrder),
    path("stocks/check/", views.checkStocks),
    path("invoices/<str:transaction_id>", views.invoice, name="invoice")
]

atay_trade/store/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class UserSignUpForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True

        self.fields['password1'].help_text = "Your password should be at least 8 characters with numbers and letters"
        self.fields['password2'].help_text = None

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'email',]
        required = ['first_name', 'last_name', 'email']
        

atay_trade/store/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse, HttpResponse
from django.db.models import Q
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.auth.decorators import login_required
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from .models import *
from .serializers import *
from .forms import *
from .utils import render_to_pdf, send_invoice_to_email
import json
import datetime
import hashlib

def store(request):
    categories = Category.objects.all()
    categoryImages = {}
    for i in categories:
        categoryImages[i.name] = CategoryImage.objects.get(category=i).resized_image.url
    
    latest_arrived_products = Product.objects.filter(discounted_price = None).order_by("-date_added")[:8]
    on_sale_products = Product.objects.exclude(discounted_price = None)[:8]
    
    productThumbnails = {}
    for p in latest_arrived_products | on_sale_products:
        productThumbnails[p.id] = [0,0]
        qs = ProductThumbnail.objects.filter(product = p)
        if len(qs) < 2:
            productThumbnails[p.id][0] = "/media/default_product_thumbnail_compressed.jpg"
            productThumbnails[p.id][1] = "/media/default_product_thumbnail_compressed.jpg"
            continue
        productThumbnails[p.id][0] = qs[0].resized_image.url
        productThumbnails[p.id][1] = qs[1].resized_image.url

    productWislistStatuses = {}
    if request.user.is_authenticated:
        customer = request.user.customer
        for p in latest_arrived_products | on_sale_products:
            qs = Wishlist.objects.filter(customer = customer, product = p)
            if len(qs) == 1:
                productWislistStatuses[p.id] = True
            elif len(qs) == 0:
                productWislistStatuses[p.id] = False   

    context = {"categories": categories, 
               "categoryImages": categoryImages, 
               "onSaleProducts": on_sale_products,  
               "latestArrivedProducts": latest_arrived_products, 
               "productThumbnails": productThumbnails,
               "productWishlistStatuses": productWislistStatuses}
    return render(request, "store/index.html", context)

class CartList(APIView):

    def get(self, request, format=None):
        if request.user.is_authenticated == False:
            try:
                cart = json.loads(request.COOKIES["cart"])
            except:
                cart = {}
            dictResponse = {"total_price": 0, "items_count": 0, "order_items" : [], "delivery_price": 0}

            for i in cart:
                try:
                    product = Product.objects.get(id=i)
                    productImages = product.images.all()
                    dictResponse["order_items"].append({
                        "product": {
                            "id": product.id,
                            "name": product.name,
                            "price": product.price,
                            "discounted_price": product.discounted_price,
                            "model_number": product.model_number,
                            "images": [
                                { "image": productImages[0].image.url }
                            ],
                        }, 
                        "quantity": cart[i]["quantity"],
                    })
                    dictResponse["items_count"] += cart[i]["quantity"]
                    if product.discounted_price is None:
                        dictResponse["total_price"] += round(product.price * cart[i]["quantity"], 2)
                    else:
                        dictResponse["total_price"] += round(product.discounted_price * cart[i]["quantity"], 2)
                    
                except Exception as e:
                    print("EXCEPTION OCCURED", e)
                    continue
            
            dictResponse["delivery_price"] = Order.get_delivery_price(dictResponse["total_price"])
            dictResponse["subtotal"] = dictResponse["total_price"] 
            dictResponse["total_price"] = dictResponse["delivery_price"] + dictResponse["subtotal"]
            return Response(dictResponse, status=status.HTTP_200_OK)

        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer = customer, status=Order.NOT_PAID_STATUS)
        serializer = OrderSerializer(order)
        serializer_data = serializer.data
        return Response(serializer_data, status=status.HTTP_200_OK)

class CartAdd(APIView):

    def post(self, request, format=None):
        if request.user.is_authenticated == False:
            return Response({}, status=status.HTTP_200_OK)

        productID = request.data["productID"]
        product = Product.objects.get(id = productID)

        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer = customer, status=Order.NOT_PAID_STATUS)
        orderItem, created = OrderItem.objects.get_or_create(order = order, product = product)
        orderItem.quantity = orderItem.quantity + 1
        orderItem.save()
        
        serializer = OrderSerializer(order)
        serializer_data = serializer.data
        return Response(serializer_data, status=status.HTTP_200_OK)

class CartRemove(APIView):

    def delete(self, request, format=None):
        if request.user.is_authenticated == False:
            return Response({}, status=status.HTTP_200_OK)

        productID = request.data["productID"]
        product = Product.objects.get(id = productID)

        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer = customer, status=Order.NOT_PAID_STATUS)
        orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)
        orderItem.delete()

        serializer = OrderSerializer(order)
        serializer_data = serializer.data
        return Response(serializer.data, status=status.HTTP_200_OK)
        
def checkout(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, status=Order.NOT_PAID_STATUS)
        order_items = order.order_items.all()
        order_total = {'total_price': order.get_cart_total_price(), 
                       'items_count': order.get_cart_items_count(), 
                       "delivery_price": Order.get_delivery_price(order.get_cart_subtotal_price()),
                       "subtotal" : order.get_cart_subtotal_price()}
        customer = {'first_name': request.user.first_name, 'last_name': request.user.last_name, 'email' : request.user.email}
        context = {'items': order_items, 'total' : order_total, 'customer': customer}
    else:
        context = {}
    return render(request, "store/checkout.html", context)

def contact(request):
    context = {}
    return render(request, "store/contact.html", context)

def catalog(request, category = None):
    page = request.GET.get("page")
    searchText = request.GET.get("search")
    sortBy = request.GET.get("sortBy")
    priceRange = request.GET.get("priceRange")
    maxPrice = 0
    minPrice = 0  

    categories = Category.objects.all()
    products = []
    if searchText is not None and searchText != "":
        vector = SearchVector("name", weight="A") + SearchVector("description", weight="B") + SearchVector("brand", weight="B")
        query = SearchQuery(searchText)
        ''' Full text search on products name and description, and product should be in the stock '''
        products = Product.objects.annotate(rank = SearchRank(vector, query)).filter(Q(rank__gte=0.2) & Q(stock__gte=1)).order_by('-rank')
        #print(products.values_list('name', 'rank'))
    else:
        if sortBy == "sale":
            products = Product.objects.filter(Q(discounted_price__isnull = False) & Q(stock__gte = 0)).order_by("-discounted_price")
        elif sortBy == "toLowerPrice":
            products = Product.objects.filter(Q(stock__gte = 1)).order_by("-price")
        elif sortBy == "toHigherPrice":
            products = Product.objects.filter(Q(stock__gte = 1)).order_by("price")
        else:
            products = Product.objects.filter(Q(stock__gte = 1)).order_by("-date_added")


    if priceRange is not None:
        prices = priceRange.split("-")
        minPrice = float(prices[0])
        maxPrice = float(prices[1])
        products = products.filter(Q(stock__gte = 1) & Q(price__gte = minPrice) & Q(price__lte=maxPrice)).order_by("price")
        sortBy = "toLowerPrice"

    productThumbnails = {}
    for p in products:
        productThumbnails[p.id] = [0,0]
        qs = ProductThumbnail.objects.filter(product = p)
        if len(qs) < 2:
            productThumbnails[p.id][0] = "/media/default_product_thumbnail_compressed.jpg"
            productThumbnails[p.id][1] = "/media/default_product_thumbnail_compressed.jpg"
            continue
        productThumbnails[p.id][0] = qs[0].resized_image.url
        productThumbnails[p.id][1] = qs[1].resized_image.url

    productWislistStatuses = {}
    if request.user.is_authenticated:
        customer = request.user.customer
        for p in products:
            qs = Wishlist.objects.filter(customer = customer, product = p)
            if len(qs) == 1:
                productWislistStatuses[p.id] = True
            elif len(qs) == 0:
                productWislistStatuses[p.id] = False 

    categoryName = None # todo remove this is useless declaration
    if category is not None and category != "":
        categoryName = category
        products = products.filter(Q(category__name__iexact = category))

    paginator = Paginator(products, 6)
    products = paginator.get_page(page)
    #print(products.object_list)
    
    context = {"categories": categories,
               "products": products, 

atay_trade/templates/store/account.html
{% extends 'base.html' %}
{% load static %}
{% load store_extras %}

{% block title %} - Account {% endblock %}

{% block store %}
    {% include 'components/breadcrumbArea.html' with title="Account History" uppercase=True %}
    <div class="content-section mt-4 mb-4" style="min-height: 400px;" >
      <h3 class="text-center font-weight-normal pt-3">{{welcome_with_full_name}}</h3> 
      {% if orders_with_order_items|length > 0 %}
        <div class="d-flex justify-content-center align-self-center pt-2 mb-5">
          <a class="btn essence-btn" style="min-width: 0 !important" href="{% url 'store:checkout' %}"> Checkout </a>
          <a class="btn essence-btn ml-2" style="min-width: 0 !important" href="{% url 'store:logout' %}"> Logout </a>
        </div>
      {% else %}
      <div class="d-flex justify-content-center align-self-center pt-2">
        <a class="btn essence-btn" style="min-width: 0 !important" href="{% url 'store:checkout' %}"> Checkout </a>
        <a class="btn essence-btn ml-2" style="min-width: 0 !important" href="{% url 'store:logout' %}"> Logout </a>
      </div>
        <div class="d-flex justify-content-center align-self-center pt-2 mb-2 mb-5">
          <a class="btn essence-btn" style="min-width: 0 !important" href="{% url 'store:catalog' %}"> Catalog </a>
        </div>
        <h5 class="text-center font-weight-light">There are no orders yet. Please check out our catalog. </h5> 
      {% endif %}

      <div class="container pt-3">
        <table class="table table-borderless table-responsive-sm" style="width: 100% !important;"  id="myTable">
          <thead class="thead-dark">
              <tr>
                  <th scope="col">#</th>
                  <th scope="col">Order Date</th>
                  <th scope="col">Transaction ID</th>
                  <th scope="col">Status</th>
                  <th scope="col">Total</th>
              </tr>
          </thead>
          <tbody class="panel">

                {% if orders_with_order_items|length < 1 %}
                <tr style="background-color: #FF084E;" data-toggle="collapse" data-target="#demo" data-parent="#myTable">
                  <td>-</td>
                  <td>-</td>
                  <td>-</td>
                  <td>-</td>
                  <td>-</td>
                </tr>
                {% endif %}
              
                {% for order_with_order_items in orders_with_order_items  %}
                <tr style="background-color: #FF084E;" data-toggle="collapse" data-target="#demo{{order_with_order_items|index:0|index:0}}" data-parent="#myTable">
                  <td>{{order_with_order_items|index:0|index:0}}</td>
                  <td>{{order_with_order_items|index:0|index:1}}</td>
                  <td>{{order_with_order_items|index:0|index:2}}</td>
                  <td>{{order_with_order_items|index:0|index:3}}</td>
                  <td>{{order_with_order_items|index:0|index:4}}</td>
                </tr>
                <tr id="demo{{order_with_order_items|index:0|index:0}}" class="collapse {{should_show}} text-primary font-bold" style="background-color: #343A40;">
                  <td colspan="1">***</td>
                  <td colspan="3">Products Summary</td>
                  <td colspan="1">{{order_with_order_items|index:0|index:4}}</td>
                </tr>
                {% for order_item in order_with_order_items|index:1 %}
                <tr id="demo{{order_with_order_items|index:0|index:0}}" class="collapse {{should_show}} text-primary" style="background-color: #f0f0f0;">
                  <td colspan="1"></td>
                  <td colspan="4"> <div class="">{{order_item.quantity}}X {{order_item.product.name}}(£{{order_item.product.price|floatformat:2}})</div> </td>
                </tr>
                {% endfor %}
              {% endfor %}
          </tbody>
        </table>
      </div>
      
    </div>
{% endblock store %}

atay_trade/templates/store/catalog.html
{% extends 'base.html' %}
{% load static %}

{% block title %} - Catalog {% endblock %}

{% block store %}
    {% include 'components/breadcrumbArea.html' with title="catalog" uppercase=True %}
    {% include 'components/shopGridArea.html' %}
{% endblock store %}

atay_trade/templates/store/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block title %} - Checkout {% endblock %}

{% block store %}
    {% include 'components/breadcrumbArea.html' with title="checkout" uppercase=True %}
    {% include 'components/checkoutArea.html' %}    
{% endblock store %}

{% block scoped_js %}
    <script type="text/javascript" src="{% static 'js/checkout.js' %}"></script>
{% endblock scoped_js %}
    
    

atay_trade/templates/store/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %} - Contact {% endblock %}

{% block store %}
    {% include 'components/contactInfo.html' %}    
{% endblock store %}
    
    

atay_trade/templates/store/index.html
{% extends 'base.html' %}

{% block title %} - Store {% endblock %}

{% block store %}
    {% include 'components/welcomeArea.html' %}
    {% include 'components/topCategoryArea.html' with categories=categories categoryImages=categoryImages %}
    {% include 'components/commonTravelArea.html' %}
    {% include 'components/arrivalsArea.html' with products=products productThumbnails=productThumbnails %}
    {% include 'components/salesArea.html' with products=products productThumbnails=productThumbnails %}
{% endblock store %}

atay_trade/templates/store/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} - Login {% endblock %}

{% block store %}

    <div class="content-section" style="width: 100%;
    max-width: 800px;
    padding: 15px;
    margin: 0 auto; 
    padding-top: 50px; 
    padding-bottom: 50px;">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group" style="display: flex;justify-content: center;">
                <button class="btn essence-btn" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2 text-danger" href="{% url 'store:signup' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
{% endblock store %}

atay_trade/templates/store/product.html
{% extends 'base.html' %}
{% load static %}

{% block title %} - Product {% endblock %}

{% block store %}
    {% include 'components/productDetailArea.html' with product=product productImages=productImages %}
{% endblock store %}

atay_trade/templates/store/signup.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} - Sign Up {% endblock %}

{% block store %}

    <div class="content-section" style="width: 100%;
    max-width: 800px;
    padding: 15px;
    margin: 0 auto; 
    padding-top: 50px; 
    padding-bottom: 50px;">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group" style="display: flex;justify-content: center;">
                <button class="btn essence-btn" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2 text-danger" href="{% url 'store:login' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock store %}

atay_trade/templates/store/wishlist.html
{% extends 'base.html' %}
{% load static %}
{% load store_extras %}

{% block title %} - Wishlist {% endblock %}

{% block store %}
    {% include 'components/breadcrumbArea.html' with title="Wishlist" uppercase=True %}
    <div class="content-section mt-4 mb-4" style="min-height: 400px;">
        
        {% if products|length < 1 %}
            <div class="d-flex justify-content-center align-self-center pt-3 mb-2 mb-5">
              <a class="btn essence-btn" style="min-width: 0 !important" href="{% url 'store:catalog' %}"> Catalog </a>
            </div>
            <h5 class="text-center font-weight-light">There are no products in your wishlist. Please check out our catalog. </h5> 
        {% endif %}
      
        <div class="container pt-3">
            <div class="card-deck">
                
                {% for product in products %}
                <div class="card my-3 border-0" style="background-color: #252525;">	
                    <a class="text-center pt-3 pb-3" href="{% url 'store:product' product.id %}" style="font-weight: 600; font-size: 1.5rem; color: #f0f0f0;">{{product.name}}</a>
                    <img class="wishlist-product-thumbnail" src="{{productThumbnails|index:product.id}}" class="card-img-top">
                    <div class="card-body btn-group">
                        <a class="btn btn-primary mt-auto" href="{% url 'store:product' product.id %}"><i class="far fa-eye fa-2x"></i></a>
                        <button class="btn btn-primary-like mt-auto" data-product="{{product.id}}"><i class="fas fa-heart fa-2x text-red wishlist-heart"></i></button>
                    </div>
                </div>   
                {% endfor %}
                     
            </div>
            
        </div>
    </div>
{% endblock store %}